### ISSUE TITLE
Avisynth 3.6 compatiblity (Access Violation)

### ISSUE THREAD

**Issue by Selur** [Kiyamou/VapourSynth-JincResize#8]
When using JincResize with Avisynth 3.6 one gets an 'Access Violation', would be nice if this could be fixed.

**Comment by Kiyamou** [comment]
I'm a little confused. How do load a VapourSynth plugins in AviSynth?
For AviSynth, there is https://github.com/AviSynth/jinc-resize.

BTW, I test jinc-resize for avs (v0.2) in AviSynth 3.6. It looks work fine.

**Comment by Selur** [comment]
Sorry, my bad mixed the Avisynth and the Vapoursynth plugins on my system. :)
